# Generated by Django 5.1.4 on 2024-12-26 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_tenth_marks', models.FloatField(blank=True, null=True)),
                ('min_higher_secondary_marks', models.FloatField(blank=True, null=True)),
                ('min_cgpa', models.FloatField()),
                ('min_attendance', models.FloatField()),
                ('is_kt', models.BooleanField(default=False)),
                ('is_backlog', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('core', 'core'), ('it', 'it')], max_length=40)),
                ('departments', models.TextField(default='all')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sr_no', models.TextField(default='')),
                ('to', models.TextField(default='')),
                ('subject', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('intro', models.TextField(default='')),
                ('eligibility_criteria', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('documents_to_carry', models.TextField(default='')),
                ('walk_in_interview', models.TextField(default='')),
                ('company_registration_link', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('from_field', models.TextField(default='')),
                ('from_designation', models.TextField(default='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_notice', to='internship.internshipregistration')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=100)),
                ('attendance', models.BooleanField(default=False)),
                ('hr_round', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_applications', to='internship.internshipregistration')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_letter', models.FileField(upload_to='offer_letters/')),
                ('type', models.CharField(default='', max_length=100)),
                ('salary', models.FloatField(default=0)),
                ('position', models.CharField(default='', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('domain_name', models.CharField(default='', max_length=100)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='internship.internshipregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('stipend', models.FloatField()),
                ('position', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_offers', to='internship.internshipregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('internship_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='internship.internshipnotice')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('internship_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='internship.internshipnotice')),
            ],
        ),
        migrations.CreateModel(
            name='Stipend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internship_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipends', to='internship.internshipnotice')),
            ],
        ),
    ]
